<a href="https://colab.research.google.com/github/lahirua-madhusanka/data_warehouse_coursework/blob/ETL_pipeline/dw_cw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Libraries**

In [12]:
import pandas as pd

**Upload dataset to the colab**

In [13]:
from google.colab import files
uploaded = files.upload()

Saving college_students_habits_1M.csv to college_students_habits_1M (1).csv

**Dataset Load**

In [9]:
df = pd.read_csv('college_students_habits_1M.csv')
df.head()

,study_hours,attendance,assignment_completion,midterm_score,final_score,project_score,backlogs,sleep_hours,stress,anxiety,...,hostel_student,extracurricular_hours,phone_unlocks_per_day,previous_gpa,class_participation,weekly_study_sessions,group_study_hours,financial_stress,gpa,performance_level
0,3.014684,67.00599,51.595387,57.211285,61.653540,65.397200,4,5.993893,4.287966,58.146000,...,0,1.958940,73.727480,5.721128,3.587111,2.814086,1.814086,5.491878,0.546729,Low
1,3.665277,73.28455,69.749020,57.552320,62.062782,65.715500,3,6.949383,1.841224,41.945290,...,0,3.146447,48.468456,5.755232,4.820090,2.836821,1.836821,2.876881,0.707133,Low
2,2.703784,72.32519,92.837640,44.568970,46.482760,53.597702,2,6.703293,3.863112,56.555750,...,1,5.551245,46.623684,4.456897,5.493774,1.971265,0.971265,5.704047,0.868230,Low
3,3.445073,74.75687,85.189026,52.040790,55.448948,60.571404,2,6.498832,5.073206,65.171420,...,1,4.543216,47.909600,5.204079,5.481987,2.469386,1.469386,6.596658,0.729216,Low
4,0.192687,55.05021,64.520620,32.815000,32.378000,42.627330,5,6.552570,1.000000,30.725826,...,1,4.447042,73.316520,3.281500,2.822375,1.187667,0.187667,4.602954,0.370964,Low

**Dataset Info**

In [10]:
#shape of the dataset
print("shape", df.shape)

#data type
print("datatype" , df.dtypes)

#summery of the dataset
df.describe()

shape (1000000, 42)
datatype study_hours                 float64
attendance                  float64
assignment_completion       float64
midterm_score               float64
final_score                 float64
project_score               float64
backlogs                      int64
sleep_hours                 float64
stress                      float64
anxiety                     float64
depression                  float64
motivation                  float64
concentration               float64
time_management             float64
self_discipline             float64
social_media_hours          float64
gaming_hours                float64
netflix_hours               float64
screen_time                 float64
physical_activity           float64
junk_food_frequency         float64
caffeine_mg                 float64
late_night_frequency        float64
procrastination_score       float64
family_income               float64
parental_education_level      int64
internet_quality            float64
library_visits              float64
online_courses_completed      int64
part_time_hours             float64
peer_study_group              int64
relationship_status           int64
hostel_student                int64
extracurricular_hours       float64
phone_unlocks_per_day       float64
previous_gpa                float64
class_participation         float64
weekly_study_sessions       float64
group_study_hours           float64
financial_stress            float64
gpa                         float64
performance_level            object
dtype: object

,study_hours,attendance,assignment_completion,midterm_score,final_score,project_score,backlogs,sleep_hours,stress,anxiety,...,relationship_status,hostel_student,extracurricular_hours,phone_unlocks_per_day,previous_gpa,class_participation,weekly_study_sessions,group_study_hours,financial_stress,gpa
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,4.042036,74.876365,69.896701,60.011309,64.856105,67.972723,2.550791,6.499550,3.211822,49.986145,...,0.309228,0.499858,2.999902,60.068814,6.001131,5.008589,3.002335,2.511193,4.998476,0.831196
std,2.212739,12.892864,14.682793,14.967273,17.606373,13.877038,1.650993,0.435650,1.756919,14.999785,...,0.462176,0.500000,0.998515,19.884181,1.496727,1.713582,1.000212,1.415504,1.340340,0.295290
min,0.000000,30.000000,20.000000,0.000000,0.000000,0.000000,0.000000,4.520054,1.000000,0.000000,...,0.000000,0.000000,0.000000,10.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
25%,2.457050,66.092450,59.909055,49.891078,52.869294,58.565006,1.000000,6.206206,1.686328,39.862051,...,0.000000,0.000000,2.324179,46.560403,4.989108,3.834943,2.326072,1.326072,4.090790,0.626618
50%,4.004593,75.027325,70.021207,60.027573,65.033085,68.025735,2.000000,6.498872,3.046761,49.973913,...,0.000000,0.000000,2.999001,60.019001,6.002757,5.003885,3.001838,3.001838,4.996261,0.830458
75%,5.552457,83.971757,80.136895,70.158226,77.189865,77.481010,4.000000,6.793280,4.410195,60.099820,...,1.000000,1.000000,3.675471,73.526887,7.015822,6.173169,3.677215,3.677215,5.903410,1.034218
max,12.000000,100.000000,100.000000,100.000000,100.000000,100.000000,10.000000,8.763114,10.000000,100.000000,...,1.000000,1.000000,7.531504,154.914220,10.000000,10.000000,8.062667,8.062667,10.000000,2.009058

**Check missing values**

In [ ]:
missing_values = df.isnull().sum()
print(missing_values)

study_hours                    0
attendance                     0
assignment_completion          0
midterm_score                  0
final_score                    0
project_score                  0
backlogs                       0
sleep_hours                    0
stress                         0
anxiety                        0
depression                     0
motivation                     0
concentration                  0
time_management                0
self_discipline                0
social_media_hours             0
gaming_hours                   0
netflix_hours                  0
screen_time                    0
physical_activity              0
junk_food_frequency            0
caffeine_mg                    0
late_night_frequency           0
procrastination_score          0
family_income                  0
parental_education_level       0
internet_quality               0
library_visits                 0
online_courses_completed       0
part_time_hours                0
peer_study_group               0
relationship_status            0
hostel_student                 0
extracurricular_hours          0
phone_unlocks_per_day          0
previous_gpa                   0
class_participation            0
weekly_study_sessions          0
group_study_hours              0
financial_stress               0
gpa                            0
performance_level           1558
dtype: int64

**drop missing values**
(here no missing values)

In [ ]:
df = df.dropna()

**Remove duplicates**

In [ ]:
df = df.drop_duplicates()
print("After Remove duplicates" ,df.shape)

After Remove duplicates (998442, 42)

**ETL Pipeline**

In [14]:
!pip install oracledb pandas

Collecting oracledb
  Downloading oracledb-3.4.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (7.7 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: cryptography>=3.2.1 in /usr/local/lib/python3.12/dist-packages (from oracledb) (43.0.3)
Requirement already satisfied: typing_extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from oracledb) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.2.1->oracledb) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.2.1->oracledb) (3.0)
Downloading oracledb-3.4.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 31.7 MB/s eta 0:00:00
Installing collected packages: oracledb
Successfully installed oracledb-3.4.2

**Uploading oracle wallet zipfile**

In [15]:
from google.colab import files
uploaded = files.upload()

Saving Wallet_studentdw.zip to Wallet_studentdw.zip

In [17]:
import pandas as pd
import numpy as np

In [18]:
import oracledb

**Extract Phase**

In [19]:
from google.colab import files
uploaded = files.upload()

Saving Cleaned_student_dataset.csv to Cleaned_student_dataset.csv

**Reading the dataset usong pandas**

In [21]:
df = pd.read_csv("Cleaned_student_dataset.csv")
print("Dataset loaded successfully")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully
Shape: (998442, 42)

,study_hours,attendance,assignment_completion,midterm_score,final_score,project_score,backlogs,sleep_hours,stress,anxiety,...,hostel_student,extracurricular_hours,phone_unlocks_per_day,previous_gpa,class_participation,weekly_study_sessions,group_study_hours,financial_stress,gpa,performance_level
0,3.014684,67.00599,51.595387,57.211285,61.653540,65.397200,4,5.993893,4.287966,58.146000,...,0,1.958940,73.727480,5.721128,3.587111,2.814086,1.814086,5.491878,0.546729,Low
1,3.665277,73.28455,69.749020,57.552320,62.062782,65.715500,3,6.949383,1.841224,41.945290,...,0,3.146447,48.468456,5.755232,4.820090,2.836821,1.836821,2.876881,0.707133,Low
2,2.703784,72.32519,92.837640,44.568970,46.482760,53.597702,2,6.703293,3.863112,56.555750,...,1,5.551245,46.623684,4.456897,5.493774,1.971265,0.971265,5.704047,0.868230,Low
3,3.445073,74.75687,85.189026,52.040790,55.448948,60.571404,2,6.498832,5.073206,65.171420,...,1,4.543216,47.909600,5.204079,5.481987,2.469386,1.469386,6.596658,0.729216,Low
4,0.192687,55.05021,64.520620,32.815000,32.378000,42.627330,5,6.552570,1.000000,30.725826,...,1,4.447042,73.316520,3.281500,2.822375,1.187667,0.187667,4.602954,0.370964,Low

**Inspect the database**

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998442 entries, 0 to 998441
Data columns (total 42 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   study_hours               998442 non-null  float64
 1   attendance                998442 non-null  float64
 2   assignment_completion     998442 non-null  float64
 3   midterm_score             998442 non-null  float64
 4   final_score               998442 non-null  float64
 5   project_score             998442 non-null  float64
 6   backlogs                  998442 non-null  int64
 7   sleep_hours               998442 non-null  float64
 8   stress                    998442 non-null  float64
 9   anxiety                   998442 non-null  float64
 10  depression                998442 non-null  float64
 11  motivation                998442 non-null  float64
 12  concentration             998442 non-null  float64
 13  time_management           998442 non-null  float64
 14  self_discipline           998442 non-null  float64
 15  social_media_hours        998442 non-null  float64
 16  gaming_hours              998442 non-null  float64
 17  netflix_hours             998442 non-null  float64
 18  screen_time               998442 non-null  float64
 19  physical_activity         998442 non-null  float64
 20  junk_food_frequency       998442 non-null  float64
 21  caffeine_mg               998442 non-null  float64
 22  late_night_frequency      998442 non-null  float64
 23  procrastination_score     998442 non-null  float64
 24  family_income             998442 non-null  float64
 25  parental_education_level  998442 non-null  int64
 26  internet_quality          998442 non-null  float64
 27  library_visits            998442 non-null  float64
 28  online_courses_completed  998442 non-null  int64
 29  part_time_hours           998442 non-null  float64
 30  peer_study_group          998442 non-null  int64
 31  relationship_status       998442 non-null  int64
 32  hostel_student            998442 non-null  int64
 33  extracurricular_hours     998442 non-null  float64
 34  phone_unlocks_per_day     998442 non-null  float64
 35  previous_gpa              998442 non-null  float64
 36  class_participation       998442 non-null  float64
 37  weekly_study_sessions     998442 non-null  float64
 38  group_study_hours         998442 non-null  float64
 39  financial_stress          998442 non-null  float64
 40  gpa                       998442 non-null  float64
 41  performance_level         998442 non-null  object
dtypes: float64(35), int64(6), object(1)
memory usage: 319.9+ MB

In [23]:
df.describe()

,study_hours,attendance,assignment_completion,midterm_score,final_score,project_score,backlogs,sleep_hours,stress,anxiety,...,relationship_status,hostel_student,extracurricular_hours,phone_unlocks_per_day,previous_gpa,class_participation,weekly_study_sessions,group_study_hours,financial_stress,gpa
count,998442.000000,998442.000000,998442.000000,998442.000000,998442.000000,998442.000000,998442.000000,998442.000000,998442.000000,998442.000000,...,998442.000000,998442.00000,998442.000000,998442.000000,998442.000000,998442.000000,998442.000000,998442.000000,998442.000000,998442.000000
mean,4.047690,74.917420,69.934501,60.054373,64.907475,68.012877,2.545442,6.500712,3.208959,49.965744,...,0.308661,0.49951,2.999572,60.038748,6.005437,5.013588,3.005179,2.514502,4.996204,0.832493
std,2.209590,12.855825,14.654863,14.932640,17.564117,13.844379,1.645927,0.434666,1.755438,14.992762,...,0.461941,0.50000,0.998513,19.868860,1.493264,1.709864,0.998007,1.413964,1.339162,0.293688
min,0.000000,30.000000,20.000000,0.000000,0.000000,0.000000,0.000000,4.540363,1.000000,0.000000,...,0.000000,0.00000,0.000000,10.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000021
25%,2.465405,66.138189,59.952564,49.942135,52.930561,58.612659,1.000000,6.207497,1.684296,39.845761,...,0.000000,0.00000,2.323855,46.540322,4.994213,3.840798,2.329476,1.329476,4.089458,0.627753
50%,4.009318,75.051935,70.047250,60.054910,65.065895,68.051252,2.000000,6.499714,3.043831,49.953350,...,0.000000,0.00000,2.998680,59.994841,6.005491,5.007232,3.003661,3.003661,4.994279,0.831056
75%,5.555103,83.986895,80.155384,70.175530,77.210634,77.497160,4.000000,6.793814,4.406149,60.078018,...,1.000000,1.00000,3.674971,73.490955,7.017553,6.175304,3.678369,3.678369,5.900833,1.034612
max,12.000000,100.000000,100.000000,100.000000,100.000000,100.000000,10.000000,8.763114,10.000000,100.000000,...,1.000000,1.00000,7.531504,154.594400,10.000000,10.000000,8.062667,8.062667,10.000000,2.009058

In [24]:
df.isnull().sum()

study_hours                 0
attendance                  0
assignment_completion       0
midterm_score               0
final_score                 0
project_score               0
backlogs                    0
sleep_hours                 0
stress                      0
anxiety                     0
depression                  0
motivation                  0
concentration               0
time_management             0
self_discipline             0
social_media_hours          0
gaming_hours                0
netflix_hours               0
screen_time                 0
physical_activity           0
junk_food_frequency         0
caffeine_mg                 0
late_night_frequency        0
procrastination_score       0
family_income               0
parental_education_level    0
internet_quality            0
library_visits              0
online_courses_completed    0
part_time_hours             0
peer_study_group            0
relationship_status         0
hostel_student              0
extracurricular_hours       0
phone_unlocks_per_day       0
previous_gpa                0
class_participation         0
weekly_study_sessions       0
group_study_hours           0
financial_stress            0
gpa                         0
performance_level           0
dtype: int64

**Transform Phase**

In [25]:
#Standardize column names
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace(r'[^a-z0-9_]', '', regex=True)

print(df.columns)

Index(['study_hours', 'attendance', 'assignment_completion', 'midterm_score',
       'final_score', 'project_score', 'backlogs', 'sleep_hours', 'stress',
       'anxiety', 'depression', 'motivation', 'concentration',
       'time_management', 'self_discipline', 'social_media_hours',
       'gaming_hours', 'netflix_hours', 'screen_time', 'physical_activity',
       'junk_food_frequency', 'caffeine_mg', 'late_night_frequency',
       'procrastination_score', 'family_income', 'parental_education_level',
       'internet_quality', 'library_visits', 'online_courses_completed',
       'part_time_hours', 'peer_study_group', 'relationship_status',
       'hostel_student', 'extracurricular_hours', 'phone_unlocks_per_day',
       'previous_gpa', 'class_participation', 'weekly_study_sessions',
       'group_study_hours', 'financial_stress', 'gpa', 'performance_level'],
      dtype='object')

In [26]:
#remove duplicate rows
print("Before removing duplicates:", df.shape)
df = df.drop_duplicates()
print("After removing duplicates:", df.shape)

Before removing duplicates: (998442, 42)
After removing duplicates: (998442, 42)

In [27]:
#Convert important columns to numeric
numeric_columns = [
    'study_hours',
    'attendance',
    'assignment_completion',
    'midterm_score',
    'final_score',
    'project_score',
    'sleep_hours',
    'stress',
    'social_media_hours',
    'physical_activity',
    'gpa'
]

for col in numeric_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

**Handle missing values**

In [28]:
df = df.dropna(subset=numeric_columns)

**Select only required columns**

In [29]:
selected_columns = [
    'study_hours',
    'attendance',
    'assignment_completion',
    'midterm_score',
    'final_score',
    'project_score',
    'sleep_hours',
    'stress',
    'social_media_hours',
    'physical_activity',
    'gpa'
]

df = df[selected_columns]
print("Final transformed shape:", df.shape)
df.head()

Final transformed shape: (998442, 11)

,study_hours,attendance,assignment_completion,midterm_score,final_score,project_score,sleep_hours,stress,social_media_hours,physical_activity,gpa
0,3.014684,67.00599,51.595387,57.211285,61.653540,65.397200,5.993893,4.287966,4.029561,3.313626,0.546729
1,3.665277,73.28455,69.749020,57.552320,62.062782,65.715500,6.949383,1.841224,2.135134,4.576577,0.707133
2,2.703784,72.32519,92.837640,44.568970,46.482760,53.597702,6.703293,3.863112,1.996776,4.668816,0.868230
3,3.445073,74.75687,85.189026,52.040790,55.448948,60.571404,6.498832,5.073206,2.093220,4.604520,0.729216
4,0.192687,55.05021,64.520620,32.815000,32.378000,42.627330,6.552570,1.000000,3.998739,3.334174,0.370964

**Save the transformed dataset**

In [30]:
df.to_csv("etl_cleaned_students.csv", index=False)
print("Transformed dataset saved successfully")

Transformed dataset saved successfully

**Load Phase**

In [31]:
from google.colab import files
uploaded = files.upload()

Saving Wallet_studentdw.zip to Wallet_studentdw (1).zip

**Extract the wallet**

In [32]:
import zipfile
import os

wallet_zip = "Wallet_studentdw.zip"
wallet_dir = "/content/wallet"

os.makedirs(wallet_dir, exist_ok=True)

with zipfile.ZipFile(wallet_zip, 'r') as zip_ref:
    zip_ref.extractall(wallet_dir)

print("Wallet extracted successfully")

Wallet extracted successfully

**Connect to Oracle ADW**

In [33]:
import oracledb

username = "ADMIN"
password = "Lm@Madush$96"
dsn = "studentdw_high"

connection = oracledb.connect(
    user=username,
    password=password,
    dsn=dsn,
    config_dir=wallet_dir,
    wallet_location=wallet_dir,
    wallet_password=password
)

print("Connected to Oracle ADW successfully")

Connected to Oracle ADW successfully

**Create Cursor**

In [34]:
cursor = connection.cursor()

**prepare Instant query**

In [35]:
insert_query = """
INSERT INTO student_performance_etl (
    study_hours,
    attendance,
    assignment_completion,
    midterm_score,
    final_score,
    project_score,
    sleep_hours,
    stress,
    social_media_hours,
    physical_activity,
    gpa
) VALUES (
    :1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11
)
"""

**Convert the DataFrame into tuples**

In [36]:
data_to_insert = [tuple(row) for row in df.to_numpy()]
print("Rows prepared for insertion:", len(data_to_insert))

Rows prepared for insertion: 998442

**Insert data in batches**

In [37]:
batch_size = 10000

for i in range(0, len(data_to_insert), batch_size):
    batch = data_to_insert[i:i + batch_size]
    cursor.executemany(insert_query, batch)
    connection.commit()
    print(f"Inserted rows {i} to {i + len(batch)}")

Inserted rows 0 to 10000
Inserted rows 10000 to 20000
Inserted rows 20000 to 30000
Inserted rows 30000 to 40000
Inserted rows 40000 to 50000
Inserted rows 50000 to 60000
Inserted rows 60000 to 70000
Inserted rows 70000 to 80000
Inserted rows 80000 to 90000
Inserted rows 90000 to 100000
Inserted rows 100000 to 110000
Inserted rows 110000 to 120000
Inserted rows 120000 to 130000
Inserted rows 130000 to 140000
Inserted rows 140000 to 150000
Inserted rows 150000 to 160000
Inserted rows 160000 to 170000
Inserted rows 170000 to 180000
Inserted rows 180000 to 190000
Inserted rows 190000 to 200000
Inserted rows 200000 to 210000
Inserted rows 210000 to 220000
Inserted rows 220000 to 230000
Inserted rows 230000 to 240000
Inserted rows 240000 to 250000
Inserted rows 250000 to 260000
Inserted rows 260000 to 270000
Inserted rows 270000 to 280000
Inserted rows 280000 to 290000
Inserted rows 290000 to 300000
Inserted rows 300000 to 310000
Inserted rows 310000 to 320000
Inserted rows 320000 to 330000
Inserted rows 330000 to 340000
Inserted rows 340000 to 350000
Inserted rows 350000 to 360000
Inserted rows 360000 to 370000
Inserted rows 370000 to 380000
Inserted rows 380000 to 390000
Inserted rows 390000 to 400000
Inserted rows 400000 to 410000
Inserted rows 410000 to 420000
Inserted rows 420000 to 430000
Inserted rows 430000 to 440000
Inserted rows 440000 to 450000
Inserted rows 450000 to 460000
Inserted rows 460000 to 470000
Inserted rows 470000 to 480000
Inserted rows 480000 to 490000
Inserted rows 490000 to 500000
Inserted rows 500000 to 510000
Inserted rows 510000 to 520000
Inserted rows 520000 to 530000
Inserted rows 530000 to 540000
Inserted rows 540000 to 550000
Inserted rows 550000 to 560000
Inserted rows 560000 to 570000
Inserted rows 570000 to 580000
Inserted rows 580000 to 590000
Inserted rows 590000 to 600000
Inserted rows 600000 to 610000
Inserted rows 610000 to 620000
Inserted rows 620000 to 630000
Inserted rows 630000 to 640000
Inserted rows 640000 to 650000
Inserted rows 650000 to 660000
Inserted rows 660000 to 670000
Inserted rows 670000 to 680000
Inserted rows 680000 to 690000
Inserted rows 690000 to 700000
Inserted rows 700000 to 710000
Inserted rows 710000 to 720000
Inserted rows 720000 to 730000
Inserted rows 730000 to 740000
Inserted rows 740000 to 750000
Inserted rows 750000 to 760000
Inserted rows 760000 to 770000
Inserted rows 770000 to 780000
Inserted rows 780000 to 790000
Inserted rows 790000 to 800000
Inserted rows 800000 to 810000
Inserted rows 810000 to 820000
Inserted rows 820000 to 830000
Inserted rows 830000 to 840000
Inserted rows 840000 to 850000
Inserted rows 850000 to 860000
Inserted rows 860000 to 870000
Inserted rows 870000 to 880000
Inserted rows 880000 to 890000
Inserted rows 890000 to 900000
Inserted rows 900000 to 910000
Inserted rows 910000 to 920000
Inserted rows 920000 to 930000
Inserted rows 930000 to 940000
Inserted rows 940000 to 950000
Inserted rows 950000 to 960000
Inserted rows 960000 to 970000
Inserted rows 970000 to 980000
Inserted rows 980000 to 990000
Inserted rows 990000 to 998442

**Verify the load**

In [38]:
cursor.execute("SELECT COUNT(*) FROM student_performance_etl")
row_count = cursor.fetchone()[0]
print("Total rows loaded into ADW:", row_count)

Total rows loaded into ADW: 998442

**Close the connection**

In [39]:
cursor.close()
connection.close()
print("Connection closed successfully")

Connection closed successfully